name: Release

on:
  push:
    branches:
      - master
    tags:
      - v*
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - freebsd
        arch:
          - amd64
          - arm64

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: |
          env GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} make

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: tarballs
          path: bin/*.tar.gz

  release:
    name: Release
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: tarballs
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: mage-*.tar.gz
          generate_release_notes: true
